---
name: "Release"

on:
  push:
    branches:
      - main

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Make prepare_release.sh executable
        run: chmod +x ./prepare_release.sh

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          extra_plugins: |
            @semantic-release/exec
            conventional-changelog-conventionalcommits@^8.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
